# Generated by Django 4.0.4 on 2022-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_libro_enlace_libro_compartido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='compartido',
        ),
        migrations.AddField(
            model_name='libro',
            name='enlace',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
