# Generated by Django 4.0.4 on 2022-06-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_libro_compartido_libro_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='compartido',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
    ]
