# Generated by Django 4.0.4 on 2022-06-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_libro_compartido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='compartido',
        ),
    ]
