# Generated by Django 4.0.4 on 2022-06-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_libro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
