# Generated by Django 4.0.4 on 2022-05-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
