# Generated by Django 4.0.4 on 2022-05-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usuarios_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
